<?php
echo "<!doctype html>\n"; 
echo "<html>\n"; 
echo "  <head>\n"; 
echo "    <meta charset=utf-8>\n"; 
echo "    <title>Salakhova A.</title>\n"; 
echo "	<style>\n"; 
echo "	body {\n"; 
echo "	background-image:url(http://s1.uploads.ru/t0hNE.jpg);\n"; 
echo "	background-repeat:no repeat;\n"; 
echo "	background-position: top center; \n"; 
echo "	background-attachment: fixed;\n"; 
echo " }\n"; 
echo "	article {\n"; 
echo "	margin-left: 150px;\n"; 
echo "	margin-right:100px;\n"; 
echo "	color: #1f1e26;\n"; 
echo "	margin-left: 25%;\n"; 
echo "	margin-right: 25%;\n"; 
echo "    font-family: Georgia;\n"; 
echo "	}\n"; 
echo "	header {\n"; 
echo "	text-align: center;\n"; 
echo "	font-variant: small-caps;\n"; 
echo "	color: #bbbbbb;\n"; 
echo "	}\n"; 
echo "	footer {\n"; 
echo "	text-size: 0.5;\n"; 
echo "	text-align: center;\n"; 
echo "	color: #bbbbbb;\n"; 
echo "	}\n"; 
echo "	h1{\n"; 
echo "    font-variant: small-caps;\n"; 
echo "    font-family: Tahoma;\n"; 
echo "    color: #2a52be;\n"; 
echo "	text-shadow:0px 1px 0px #d5d5d5;\n"; 
echo "    font-size: 140%;\n"; 
echo "    background-color : none;\n"; 
echo "    text-align: center;\n"; 
echo "    }\n"; 
echo "	h2{\n"; 
echo "    font-variant: normal;\n"; 
echo "    font-family: Tahoma;\n"; 
echo "    color: #505050;\n"; 
echo "	text-shadow:0px 1px 0px #ffffff;\n"; 
echo "    font-size: 120%;\n"; 
echo "    background-color : none;\n"; 
echo "    text-align: center;\n"; 
echo "    }\n"; 
echo "	</style>\n"; 
echo "  </head>\n"; 
echo "  <body>\n"; 
echo "     <header>\n"; 
echo "      <hgroup>\n"; 
echo "         <h1>Salakhova A. </h1>\n"; 
echo "         <h2>angenzel@gmail.com</h2>\n"; 
echo "      </hgroup>\n"; 
echo "    </header>\n"; 
echo " <center><img src=\"http://s6.uploads.ru/MDZHK.jpg\" ></img></center>\n"; 
echo "	<article>\n"; 
echo "<B>Good evening!</B></br>\n"; 
echo "My name is Alyona (Helen). I am a student of MPSU  and I will be a teacher of Math and Computer Systems at the school. I was born in 1994.<br>\n"; 
echo "I have interested in IT science 2003, my first computer was bought by my parents at 2000. Now I work as Freelancer. </article></br>\n"; 
echo "<article>\n"; 
echo "I am bad in German, sorry. <b> This page is so pure because it`s just test for  using GIT.\n"; 
echo "</article>\n"; 
echo "\n"; 
echo "\n"; 
echo "<footer>Salakhova A. \n"; 
echo "</footer>\n"; 
echo "	</body>\n"; 
echo "	</html>\n"; 
echo "\n"; 
echo "\n";
?>

